### ISSUE TITLE
Error when computing cost

### ISSUE THREAD

**Issue by alexouzounis** [infracost/infracost#10]
Hi @aliscott - first of all, great project and thanks for sharing it with the community.

We tried using `infracost` in one of our projects and are getting the following errors. Let us know if there is anything else we can provide to help debug. We could also be using the tool wrongly to be fair :)
The infra we tested it against is not overly complex but it has a fair chunk of modules so it might be more than has been tested - not sure.

Generated plan files as following:
```
terraform plan --var-file=env/$(ENV)/vars.tfvars --out=plan.save
terraform show --json $(ENV)-plan.save > plan.json
```

Size of plan files - json plan file is about 13k lines
```
-rw-r--r--   1 alexouzounis  staff   429K 20 Jul 14:47 plan.json
-rw-r--r--   1 alexouzounis  staff    82K 20 Jul 14:47 plan.save
```

Commands executed, tried both ways:
```
╰─ infracost --tfdir=. --tfplan=plan.save
INFO Running command: /usr/local/bin/terraform show -json olaf-plan.save 
ERROR Error while reading from Writer: bufio.Scanner: token too long 
signal: broken pipe
```
and
```
╰─ infracost --tfdir=. --tfjson=plan.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x136d8c6]
goroutine 1 [running]:
infracost/internal/terraform/aws.(*Ec2AutoscalingGroup).PriceComponents(0xc0002c1400, 0x0, 0x0, 0x18271d8)
        /Users/ali/src/infracost/internal/terraform/aws/ec2_autoscaling_group.go:105 +0x26
infracost/pkg/base.(*GraphQLQueryRunner).batchQueries(0xc0002f5280, 0x1535500, 0xc0002c1400, 0x1, 0xc00021c640, 0x1, 0x1, 0xc0002cc060, 0x0)
        /Users/ali/src/infracost/pkg/base/query.go:91 +0x96
infracost/pkg/base.(*GraphQLQueryRunner).RunQueries(0xc0002f5280, 0x1535500, 0xc0002c1400, 0xc0002e4001, 0x78, 0x0)
        /Users/ali/src/infracost/pkg/base/query.go:124 +0x5a
infracost/pkg/base.GenerateCostBreakdowns(0x152b0c0, 0xc0002f5280, 0xc000038600, 0x6, 0x8, 0xc00002c300, 0x30, 0x0, 0x18, 0xc00000ef00)
        /Users/ali/src/infracost/pkg/base/costs.go:93 +0x636
main.main.func2(0xc000090b00, 0xc00000ef00, 0xe)
        /Users/ali/src/infracost/cmd/infracost/main.go:129 +0x389
github.com/urfave/cli/v2.(*App).RunContext(0xc000001980, 0x1532ea0, 0xc000028080, 0xc0000201b0, 0x3, 0x3, 0x0, 0x0)
        /Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x6be
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/ali/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /Users/ali/src/infracost/cmd/infracost/main.go:153 +0x5d1
```

**Comment by aliscott** [comment]
Thank you!

I've pushed a fix for the first issue (https://github.com/aliscott/infracost/pull/11) and released it in [v0.3.1](https://github.com/aliscott/infracost/releases/tag/v0.3.1)

For the second issue do you have examples of the `aws_autoscaling_group` resources you have?

**Comment by alexouzounis** [comment]
sure - the stack brings up an eks cluster amonst other things and we create a couple of ASGs, one for spot and one for ondemand - spot example snippet below
```

resource "aws_autoscaling_group" "spot_workers" {
  count       = length(var.private_subnets)
  depends_on  = [null_resource.delay_node_groups]
  name_prefix = "${var.cluster_name}-${count.index}"

  desired_capacity = var.spot_desired_workers
  max_size         = var.spot_max_workers
  min_size         = var.spot_min_workers
  force_delete     = false

  vpc_zone_identifier = [var.private_subnets[count.index]]
  suspended_processes = ["AZRebalance"]

  tags = [
    {
      "key"                 = "Name"
      "value"               = "${var.cluster_name}-spot-${count.index}"
      "propagate_at_launch" = true
    },
    {
      "key"                 = "kubernetes.io/cluster/${var.cluster_name}"
      "value"               = "owned"
      "propagate_at_launch" = true
    },
    {
      "key"                 = "k8s.io/cluster/${var.cluster_name}"
      "value"               = "owned"
      "propagate_at_launch" = true
    },
    {
      "key"                 = "k8s.io/cluster-autoscaler/enabled"
      "value"               = "true"
      "propagate_at_launch" = true
    },
    {
      "key"                 = "k8s.io/cluster-autoscaler/${var.cluster_name}"
      "value"               = "true"
      "propagate_at_launch" = true
    },
    {
      "key"                 = "ENV"
      "value"               = var.env
      "propagate_at_launch" = true
    },
    {
      "key"                 = "SYSTEM"
      "value"               = var.system
      "propagate_at_launch" = true
    },
    {
      "key"                 = "OWNER"
      "value"               = var.owner
      "propagate_at_launch" = true
    },
  ]

  lifecycle {
    create_before_destroy = true
    ignore_changes        = [desired_capacity]
  }

  mixed_instances_policy {
    instances_distribution {
      spot_allocation_strategy                 = "lowest-price"
      spot_instance_pools                      = 10
      spot_max_price                           = ""
      on_demand_percentage_above_base_capacity = 0
    }

    launch_template {
      launch_template_specification {
        launch_template_id = aws_launch_template.workers_launch_template.*.id[count.index]
        version            = "$Latest"
      }

      dynamic "override" {
        for_each = var.instance_types

        content {
          instance_type = override.value
        }
      }

    }
  }
}

```

**Comment by aliscott** [comment]
@alexouzounis can you try [v0.4.0](https://github.com/aliscott/infracost/releases/tag/v0.4.0)? I've added support for mixed instance policies and basic support for EC2 spot pricing.

A couple of questions regarding expected functionality for these use cases:

1. For mixed instance policies, how would you expect the instance type overrides to be represented? Currently I'm only using price for the the first override value.

2. How would you expect spot prices to be calculated? Currently I'm using the current spot price, but only refreshing it once per hour. Would you want the current spot price, an average over the last 30 days or this to be priced using the maximum spot price?

**Comment by joeunrue** [comment]
I know you weren't asking me, but if you were I'd suggest a config file where you can define what you want for spot pricing. I'd also love to see the ability to override pricing in said config file if I do have a reserved instance or if the lookup api can't find the instance type

**Comment by alexouzounis** [comment]
Hi @aliscott - can confirm that infracost is completing successfully now. Not sure whether the output is expected though. should the ec2 instances have a cost of 0 ?
```
╰─ infracost --tfdir=. --tfjson=plan.json
  NAME                                                           QUANTITY  UNIT  HOURLY COST  MONTHLY COST

  module.eks_workers.aws_autoscaling_group.on_demand_workers[0]
  Total                                                                               0.0000        0.0000

  module.eks_workers.aws_autoscaling_group.spot_workers[0]
  Total                                                                               0.0000        0.0000

  module.nat_gateway.aws_nat_gateway.nat_gw[0]
  └─ Hours                                                            730  hour       0.0450       32.8500
  Total                                                                               0.0450       32.8500

  module.nat_gateway.aws_nat_gateway.nat_gw[1]
  └─ Hours                                                            730  hour       0.0450       32.8500
  Total                                                                               0.0450       32.8500

  OVERALL TOTAL                                                                       0.0900       65.7000
```

**Comment by aliscott** [comment]
Zero costs have been fixed in https://github.com/infracost/infracost/pull/72. I used https://gist.github.com/aliscott/0d5a0da6189eaf57fbbd86bec6746612 as the test case for this.
