### ISSUE TITLE
Show user-friendly error when AWS creds not provided

### ISSUE THREAD

**Issue by MaxymVlasov** [infracost/infracost#1081]
```bash
Detected Terraform directory at ./environment/qa
  ✖ Running terraform plan 

  Terraform command failed with:
    Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.
    Error: NoCredentialProviders: no valid providers in chain
    caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
    SharedCredsLoad: failed to load profile, admin@account-name.
    EC2RoleRequestError: no EC2 instance role found
    caused by: RequestError: send request failed
    caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
      on providers.tf line 1, in provider "aws":
       1: provider "aws" {


Error: An unexpected error occurred

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.2/x64/src/runtime/debug/stack.go:24 +0x65
main.handleUnexpectedErr(0xc00018c5a0, {0x1007da0, 0x1c68dc0})
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:180 +0x92
main.main.func1()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:42 +0x69
panic({0x1007da0, 0x1c68dc0})
        /opt/hostedtoolcache/go/1.17.2/x64/src/runtime/panic.go:1038 +0x215
github.com/infracost/infracost/internal/ui.(*Spinner).Fail(0xc0002243c0)
        /home/runner/work/infracost/infracost/internal/ui/spin.go:55 +0x26
main.runMain(0x14f44a0, 0xc00032c4c0)
        /home/runner/work/infracost/infracost/cmd/infracost/run.go:219 +0x1c66
main.breakdownCmd.func1(0xc00034a500, {0x1316ae2, 0x5, 0x5})
        /home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:42 +0x15c
github.com/spf13/cobra.(*Command).execute(0xc00034a500, {0xc00033cb90, 0x5, 0x5})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000327400)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:55 +0x116

Environment:
Infracost v0.9.11

Please copy the above output and create a new issue at https://github.com/infracost/infracost/issues/new
```

**Comment by tim775** [comment]
This is live in 0.9.13.  Thanks @MaxymVlasov !
