### ISSUE TITLE
Infracost panic using a cty.Null value as a string

### ISSUE THREAD

**Issue by pickgr** [infracost/infracost#1715]
```
$ infracost breakdown --path .
Evaluating Terraform directory at .
  ✔ Downloading Terraform modules
  ✔ Evaluating Terraform directory

Error: An unexpected error occurred

value is null
goroutine 11 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.(*parallelRunner).run.func1.1()
	github.com/infracost/infracost/cmd/infracost/run.go:298 +0x46
panic({0x26d2d60, 0x30d41a0})
	runtime/panic.go:838 +0x207
github.com/zclconf/go-cty/cty.Value.AsString({{{0x30eeb50?, 0xc0002585fa?}}, {0x0?, 0x0?}})
	github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1259 +0x125
github.com/infracost/infracost/internal/hcl.(*Reference).SetKey(0xc00018c380, {{{0x30eeb50?, 0xc0002585fa?}}, {0x0?, 0x0?}})
	github.com/infracost/infracost/internal/hcl/reference.go:71 +0xd8
github.com/infracost/infracost/internal/hcl.(*Attribute).referencesFromExpression(0xc0006df248, {0x30ed848?, 0xc000122fc0})
	github.com/infracost/infracost/internal/hcl/attribute.go:248 +0x64c
github.com/infracost/infracost/internal/hcl.(*Attribute).AllReferences(...)
	github.com/infracost/infracost/internal/hcl/attribute.go:187
github.com/infracost/infracost/internal/hcl.referencedBlocks.Less({0xc000191340, 0x2b, 0x8?}, 0x39?, 0x0)
	github.com/infracost/infracost/internal/hcl/block.go:89 +0xcc
sort.medianOfThree({0x30eca58, 0xc00081dc80}, 0x8?, 0x203000?, 0x203000?)
	sort/sort.go:93 +0x7c
sort.doPivot({0x30eca58, 0xc00081dc80}, 0x0, 0x2b)
	sort/sort.go:114 +0x72
sort.quickSort({0x30eca58, 0xc00081dc80}, 0x18?, 0x273adc0?, 0xc0005a2a01?)
	sort/sort.go:203 +0x6c
sort.Sort({0x30eca58, 0xc00081dc80})
	sort/sort.go:231 +0x53
github.com/infracost/infracost/internal/hcl.Blocks.ModuleBlocks({0xc0001b1000, 0xc3, 0x30eec30?})
	github.com/infracost/infracost/internal/hcl/block.go:117 +0x1a5
github.com/infracost/infracost/internal/hcl.(*Evaluator).loadModules(0xc000683680)
	github.com/infracost/infracost/internal/hcl/evaluator.go:564 +0x45
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc000683680)
	github.com/infracost/infracost/internal/hcl/evaluator.go:138 +0xd2
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateModules(0xc0007a7200)
	github.com/infracost/infracost/internal/hcl/evaluator.go:234 +0x312
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateStep(0xc0007a7200, 0x0)
	github.com/infracost/infracost/internal/hcl/evaluator.go:197 +0x3b3
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluate(0xc0007a7200, {0x0?, 0x0?, 0x0?})
	github.com/infracost/infracost/internal/hcl/evaluator.go:164 +0x7c
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc0007a7200)
	github.com/infracost/infracost/internal/hcl/evaluator.go:139 +0x108
github.com/infracost/infracost/internal/hcl.(*Parser).ParseDirectory(0xc0003abe00)
	github.com/infracost/infracost/internal/hcl/parser.go:304 +0x49e
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).Modules(0xc0004294a0)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:231 +0x139
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadPlanJSONs(0xc0004294a0)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:199 +0x4a
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadResources(0xc0001a8900?, 0xc00000e020?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:154 +0x35
main.(*parallelRunner).runProjectConfig(0xc0003987e0, 0xc000215240)
	github.com/infracost/infracost/cmd/infracost/run.go:461 +0x1109
main.(*parallelRunner).run.func1()
	github.com/infracost/infracost/cmd/infracost/run.go:304 +0x1c5
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

Environment:
Infracost v0.10.1
```

**Comment by pickgr** [comment]
I have been able to run infracost successfully in some other directories.  The difference may be that they are not using terraform workspaces:

https://www.terraform.io/language/state/workspaces#using-workspaces

Please let me know if I can help reproduce this.  I can't share all of my code, but perhaps there is a sanitized version that will help reproduce it.

**Comment by tim775** [comment]
Thanks @pickgr.  If you could get us a sanitized version that reproduces, that would be amazing.  In the meantime if you could re-run with `--log-level=debug` and share the output that may help us track it down too.

**Comment by hugorut** [comment]
@pickgr, thanks for raising this issue. I believe we've found the problem, but could I ask you to test something for me? Could you downgrade your `infracost` CLI to version `0.10.0` and rerun it in the problem directory? Please report back if this resolves this issue or gives any new errors. Many thanks

**Comment by pickgr** [comment]
@hugorut downgrading to version `0.10.0` does indeed fix the issue.  Thanks for addressing this so quickly.  Do you happen to know if there's a way to specify a version like this with the GitHub action?

**Comment by alikhajeh1** [comment]
@pickgr yep! The [infracost/setup](https://github.com/infracost/actions/tree/master/setup#inputs) action has a `version` input that you can use to lock it:
```
steps:
  - name: Setup Infracost
    uses: infracost/actions/setup@v2
    with:
      api-key: ${{ secrets.INFRACOST_API_KEY }}
      version: 0.10.0
```

GitHub Enterprise users that use [our docker images](https://www.infracost.io/docs/integrations/cicd/#other-cicd-systems) can also lock the image version/tag.
