### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jgrumboe** [infracost/infracost#1789]
Infracost version v0.16.0

For some modules I use I got the following error message in the debug log:
```
time="2022-06-29T14:40:03+02:00" level=debug parser=terraform_hcl msg="could not evaluate value for attr: id err: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
runtime/debug.Stack()
    runtime/debug/stack.go:24 +0x65
github.com/infracost/infracost/internal/hcl.(*Attribute).value.func1()
    github.com/infracost/infracost/internal/hcl/attribute.go:71 +0x79
panic({0x2995700, 0x4203840})
    runtime/panic.go:838 +0x207
github.com/zclconf/go-cty/cty.Type.FriendlyName(...)
    github.com/zclconf/go-cty@v1.10.0/cty/type.go:47
github.com/hashicorp/hcl/v2/hclsyntax.describeConditionalTypeMismatch({{0x32d5ca0?, 0xc0001a81d5?}}, {{0x0?, 0x0?}})
    github.com/hashicorp/hcl/v2@v2.12.0/hclsyntax/expression.go:834 +0x418
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0006de3f0, 0xc0005412c0)
    github.com/hashicorp/hcl/v2@v2.12.0/hclsyntax/expression.go:620 +0x1306
github.com/infracost/infracost/internal/hcl.(*Attribute).value(0xc000c00c20, 0x0)
    github.com/infracost/infracost/internal/hcl/attribute.go:77 +0xce
github.com/infracost/infracost/internal/hcl.(*Attribute).Value(...)
    github.com/infracost/infracost/internal/hcl/attribute.go:65
github.com/infracost/infracost/internal/hcl.(*Block).Values(0xc000c9e8e0?)
    github.com/infracost/infracost/internal/hcl/block.go:740 +0xf0
github.com/infracost/infracost/internal/hcl.(*Evaluator).getValuesByBlockType(0xc0009d05a0, {0x2e86fa4, 0x6})
    github.com/infracost/infracost/internal/hcl/evaluator.go:469 +0x285
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateStep(0xc0009d05a0, 0x1)
    github.com/infracost/infracost/internal/hcl/evaluator.go:192 +0x14b
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluate(0xc0009d05a0, {0x0?, 0x0?, 0x0?})
    github.com/infracost/infracost/internal/hcl/evaluator.go:170 +0x7c
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc0009d05a0)
    github.com/infracost/infracost/internal/hcl/evaluator.go:141 +0xc5
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateModules(0xc0009d0000)
    github.com/infracost/infracost/internal/hcl/evaluator.go:240 +0x333
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateStep(0xc0009d0000, 0x0)
    github.com/infracost/infracost/internal/hcl/evaluator.go:203 +0x3b3
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluate(0xc0009d0000, {0x0?, 0x0?, 0x0?})
    github.com/infracost/infracost/internal/hcl/evaluator.go:170 +0x7c
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc0009d0000)
    github.com/infracost/infracost/internal/hcl/evaluator.go:145 +0x108
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateModules(0xc0006f7d40)
    github.com/infracost/infracost/internal/hcl/evaluator.go:240 +0x333
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluateStep(0xc0006f7d40, 0x0)
    github.com/infracost/infracost/internal/hcl/evaluator.go:203 +0x3b3
github.com/infracost/infracost/internal/hcl.(*Evaluator).evaluate(0xc0006f7d40, {0x0?, 0x0?, 0x0?})
    github.com/infracost/infracost/internal/hcl/evaluator.go:170 +0x7c
github.com/infracost/infracost/internal/hcl.(*Evaluator).Run(0xc0006f7d40)
    github.com/infracost/infracost/internal/hcl/evaluator.go:145 +0x108
github.com/infracost/infracost/internal/hcl.(*Parser).ParseDirectory(0xc0008a4580)
    github.com/infracost/infracost/internal/hcl/parser.go:329 +0x4b0
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).Modules(0xc000515b60)
    github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:248 +0x139
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadPlanJSONs(0xc000515b60)
    github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:216 +0x4a
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadResources(0xc000138780?, 0x4?)
    github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:171 +0x35
main.(*parallelRunner).runProjectConfig(0xc00037f260, 0xc000798000)
    github.com/infracost/infracost/cmd/infracost/run.go:474 +0x1269
main.(*parallelRunner).run.func1()
    github.com/infracost/infracost/cmd/infracost/run.go:310 +0x1c5
golang.org/x/sync/errgroup.(*Group).Go.func1()
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
"
```

The module uses https://github.com/cloudposse/terraform-terraform-label inside to generate labels.

For testing I narrowed it down to the following code snippets I put into a `main.tf` file with no other files in the same directory.
Then I run `infracost breakdown --path . --log-level debug`.

Failing snippet:
```
locals {
  original_tags    = "test"
  transformed_tags = local.original_tags
  id = var.enabled ? local.transformed_tags : "test3"
}
```

Working snippet:
```
locals {
  original_tags    = "test"
  transformed_tags = local.original_tags
  id = local.transformed_tags
}
```

Also working snippet:
```
locals {
  original_tags    = "test"
  transformed_tags = "test2"
  id = var.enabled ? local.transformed_tags : "test3"
}
```

Hope that helps.

**Comment by aliscott** [comment]
Thanks for adding the test case @jgrumboe! After investigating this we concluded the panic log is a non-issue and the parsing still works after this for this case. We make multiple passes over the HCL to find the correct value of the `id` variable. For this case, in the first pass the underlying hcl library throws a panic, but the correct value gets set in the second pass once the `transformed_tags` value has been set. We still want to debug log the panic stacktraces for debugging purposes but it's not trivial to exclude them for this case. Instead we've done the following for now:
1. Clarify in the log message that it can be ignored: https://github.com/infracost/infracost/pull/1859#pullrequestreview-1038901621
2. Submit a PR to the underlying `go-cty` lib to fix an issue there that is causing the panic (https://github.com/zclconf/go-cty/pull/128).
