### ISSUE TITLE
`interface conversion` panic in HCL provider

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1871]
Version: v0.10.7

Stacktrace:
```
interface conversion: interface {} is json.RawMessage, not []interface {}
goroutine 69 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
main.(*parallelRunner).run.func1.1()
	github.com/infracost/infracost/cmd/infracost/run.go:304 +0x40
panic({0x1064980c0, 0x14000def650})
	runtime/panic.go:838 +0x204
github.com/infracost/infracost/internal/providers/terraform.marshalBlock(0x14000661bf0?, 0x5?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:545 +0x350
github.com/infracost/infracost/internal/providers/terraform.marshalBlock(0x140006619d8?, 0x8?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:541 +0x140
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).getResourceOutput(_, _)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:373 +0x3bc
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).marshalModule(0x140009dc3c0, 0x1400075fa18)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:312 +0x1f0
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).modulesToPlanJSON(0x140009dc3c0, 0x12f1e9d38?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:283 +0x158
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadPlanJSONs(0x140009dc3c0)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:206 +0x98
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadResources(0x140004a5080?, 0x4?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:155 +0x28
main.(*parallelRunner).runProjectConfig(0x140004e7770, 0x140003d1d80)
	github.com/infracost/infracost/cmd/infracost/run.go:474 +0xf40
main.(*parallelRunner).run.func1()
	github.com/infracost/infracost/cmd/infracost/run.go:310 +0x190
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa8
```

**Comment by aliscott** [comment]
This is now fixed in the [v0.10.9](https://github.com/infracost/infracost/releases/tag/v0.10.9) release.
