### ISSUE TITLE
`index out of range [1] with length 1` panic in for AWS CodeBuildProject

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1874]
Version: v0.10.7

Stacktrace:
```
runtime error: index out of range [1] with length 1
goroutine 22 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
main.(*parallelRunner).run.func1.1()
	github.com/infracost/infracost/cmd/infracost/run.go:304 +0x40
panic({0x10249bdc0, 0x14001bf1998})
	runtime/panic.go:838 +0x204
github.com/infracost/infracost/internal/resources/aws.(*CodeBuildProject).nameLabel(0x14000307400?)
	github.com/infracost/infracost/internal/resources/aws/codebuild_project.go:71 +0x1f0
github.com/infracost/infracost/internal/resources/aws.(*CodeBuildProject).BuildResource(0x14000307400)
	github.com/infracost/infracost/internal/resources/aws/codebuild_project.go:40 +0xa4
github.com/infracost/infracost/internal/providers/terraform/aws.NewCodeBuildProject(0x140009bbce0, 0x140033d80c0?)
	github.com/infracost/infracost/internal/providers/terraform/aws/codebuild_project.go:23 +0x38c
github.com/infracost/infracost/internal/providers/terraform.(*Parser).createResource(0x140009367c0, 0x140009bbce0, 0x0)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:57 +0xe0
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSONResources(_, _, {_, _, _}, _, {_, {_, _}, {_, ...}, ...}, ...)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:105 +0x404
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSON(0x140009367c0, {0x14002c1e000, 0x212e9, 0x41402}, 0x14000182d00?)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:145 +0x3dc
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).parseResources(0x14000637b00, {0x140000553e0?, 0x1006564c0?}, {0x14002c1e000, 0x212e9, 0x41402}, 0x1400090f938?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:181 +0x150
github.com/infracost/infracost/internal/providers/terraform.(*HCLProvider).LoadResources(0x1400091cfc0?, 0x4?)
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:162 +0xe4
main.(*parallelRunner).runProjectConfig(0x140000b0600, 0x14000433800)
	github.com/infracost/infracost/cmd/infracost/run.go:474 +0xf40
main.(*parallelRunner).run.func1()
	github.com/infracost/infracost/cmd/infracost/run.go:310 +0x190
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa8
```

**Comment by aliscott** [comment]
This is now fixed in the [v0.10.9](https://github.com/infracost/infracost/releases/tag/v0.10.9) release.
