### ISSUE TITLE
`decimal division by 0` panic

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1875]
Version: v0.10.7

Stack trace:
```
decimal division by 0
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65
main.Run.func1()
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:65 +0x7b
panic({0x230d060, 0x2e1c860})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/shopspring/decimal.Decimal.QuoRem({0xc00008abc0, 0x1}, {0xc000e6c8e0, 0x0}, 0x10)
	/home/runner/go/pkg/mod/github.com/shopspring/decimal@v1.3.1/decimal.go:565 +0x2c5
github.com/shopspring/decimal.Decimal.DivRound({0xc00008abc0?, 0x2f6ff8?}, {0xc000e6c8e0?, 0x50?}, 0x10)
	/home/runner/go/pkg/mod/github.com/shopspring/decimal@v1.3.1/decimal.go:607 +0x56
github.com/shopspring/decimal.Decimal.Div(...)
	/home/runner/go/pkg/mod/github.com/shopspring/decimal@v1.3.1/decimal.go:552
github.com/infracost/infracost/internal/schema.(*CostComponent).UnitMultiplierHourlyQuantity(0xc000350fa0)
	/home/runner/work/infracost/infracost/internal/schema/cost_component.go:75 +0x65
github.com/infracost/infracost/internal/output.outputResource(0xc001150b00)
	/home/runner/work/infracost/infracost/internal/output/output.go:283 +0x105
github.com/infracost/infracost/internal/output.outputBreakdown({0xc0015da680, 0x7, 0xc00008abc0?})
	/home/runner/work/infracost/infracost/internal/output/output.go:263 +0xa5
github.com/infracost/infracost/internal/output.ToOutputFormat({0xc00164e100, 0x19, 0x400?})
	/home/runner/work/infracost/infracost/internal/output/output.go:346 +0x44d
main.runMain(0x2e2b500?, 0xc000591000)
	/home/runner/work/infracost/infracost/cmd/infracost/run.go:134 +0x40b
main.breakdownCmd.func1(0xc000338a00?, {0x29470bd?, 0x6?, 0x6?})
	/home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:43 +0x12a
github.com/spf13/cobra.(*Command).execute(0xc000338a00, {0xc000644060, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002f9400)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.Run(0x0, 0x0)
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:83 +0x185
main.main()
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:31 +0x1d
```

`c. UnitMultiplier` should never by zero on [this line](https://github.com/infracost/infracost/blob/f49bbde19fa417f774ed1847924e1183171d95ef/internal/schema/cost_component.go#L75) because we set it for every cost component. One fix here would be to check it and default it to 1 if it is zero, but this probably won't solve the underlying issue.

We might want to add more context to the error initially so we can track which resource it is coming from and try and fix the root error.

**Comment by alikhajeh1** [comment]
Can we close this issue?
