### ISSUE TITLE
`value is unknown` panic in HCL parser

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1876]
Version: v0.10.7

Stacktrace:
```
value is unknown
goroutine 36 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.(*parallelRunner).run.func1.1()
	github.com/infracost/infracost/cmd/infracost/run.go:304 +0x46
panic({0x2858340, 0x3360450})
	runtime/panic.go:838 +0x207
github.com/zclconf/go-cty/cty.Value.AsString({{{0x337cf80?, 0xc00027c21d?}}, {0x2956420?, 0x4383080?}})
	github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1262 +0x111
github.com/infracost/infracost/internal/hcl.(*projectLocator).walkPaths(0xc000b9f688, {0xc000856660, 0x52}, 0x3)
	github.com/infracost/infracost/internal/hcl/parser.go:655 +0x5e5
github.com/infracost/infracost/internal/hcl.(*projectLocator).walkPaths(0xc000b9f688, {0xc0000594a0, 0x49}, 0x2)
	github.com/infracost/infracost/internal/hcl/parser.go:671 +0x3da
github.com/infracost/infracost/internal/hcl.(*projectLocator).walkPaths(0xc000b9f688, {0xc000837f00, 0x32}, 0x1)
	github.com/infracost/infracost/internal/hcl/parser.go:671 +0x3da
github.com/infracost/infracost/internal/hcl.(*projectLocator).walkPaths(0xc000b9f688, {0x7ff7bfeff97b, 0x26}, 0x0)
	github.com/infracost/infracost/internal/hcl/parser.go:671 +0x3da
github.com/infracost/infracost/internal/hcl.(*projectLocator).findRootModules(0xc000b9f688, {0x7ff7bfeff97b, 0x26})
	github.com/infracost/infracost/internal/hcl/parser.go:579 +0x69
github.com/infracost/infracost/internal/hcl.LoadParsers({0x7ff7bfeff97b, 0x26}, {0x4384158, 0x0, 0x0}, {0xc00098e3c0, 0x4, 0x6})
	github.com/infracost/infracost/internal/hcl/parser.go:205 +0x125
github.com/infracost/infracost/internal/providers/terraform.NewHCLProvider(0xc000248980, 0x26?, {0xc0005b3980, 0x2, 0x0?})
	github.com/infracost/infracost/internal/providers/terraform/hcl_provider.go:121 +0x715
github.com/infracost/infracost/internal/providers.Detect(0xc000248980, 0x1)
	github.com/infracost/infracost/internal/providers/detect.go:57 +0x46f
main.(*parallelRunner).runProjectConfig(0xc00018d6e0, 0xc000248980)
	github.com/infracost/infracost/cmd/infracost/run.go:357 +0x135
main.(*parallelRunner).run.func1()
	github.com/infracost/infracost/cmd/infracost/run.go:310 +0x1c5
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa5
```

**Comment by aliscott** [comment]
This is now fixed in the [v0.10.9](https://github.com/infracost/infracost/releases/tag/v0.10.9) release.
