### ISSUE TITLE
panic: `invalid memory address or nil pointer dereference` with aws_data_transfer

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#1931]
Infracost version: v0.10.8

Stacktrace:
(I've fixed to get the actual file paths in https://github.com/infracost/infracost/pull/1929)
```
"1: running [Created by errgroup.(*Group).Go @ errgroup.go:72]
   runtime/debug:24                                                   Stack()
   main:297                                                           (*parallelRunner).run.func1.1()
   :838                                                               panic()
   github.com/infracost/infracost/internal/schema:24                  (*UsageData).Get()
   github.com/infracost/infracost/internal/providers/terraform/aws:18 newDataTransfer()
   github.com/infracost/infracost/internal/providers/terraform:57     (*Parser).createResource()
   github.com/infracost/infracost/internal/providers/terraform:105    (*Parser).parseJSONResources()
   github.com/infracost/infracost/internal/providers/terraform:145    (*Parser).parseJSON()
   github.com/infracost/infracost/internal/providers/terraform:186    (*HCLProvider).parseResources()
   github.com/infracost/infracost/internal/providers/terraform:167    (*HCLProvider).LoadResources()
   main:469                                                           (*parallelRunner).runProjectConfig()
   main:305                                                           (*parallelRunner).run.func1()
   golang.org/x/sync/errgroup:75                                      (*Group).Go.func1()
```

**Comment by mrhr7** [comment]
Hi, 

we have experienced the same error message but not using the `aws_data_transfer` any where in the code. 
Here is the output error. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x712bf6]

goroutine 9 [running]:
net/http.http2configureTransports(0x37951c0)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:6919 +0x176
net/http.(*Transport).onceSetNextProtoDefaults(0x37951c0)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:399 +0x2be
sync.(*Once).doSlow(0x7?, 0x5?)
 /opt/hostedtoolcache/go/1.18.5/x64/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
 /opt/hostedtoolcache/go/1.18.5/x64/src/sync/once.go:59
net/http.(*Transport).roundTrip(0x37951c0, 0xc000174000)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:505 +0x7c
net/http.(*Transport).RoundTrip(0x41778b?, 0x27b3040?)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000174000, {0x27b3040, 0x37951c0}, {0x2258220?, 0x1?, 0x0?})
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0x37c9440, 0xc000174000, {0x203000?, 0xc000174000?, 0x0?})
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x37c9440, 0xc000174000)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:593
net/http.(*Client).Get(0xc000080cd8?, {0x238a648?, 0x22e5018?})
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:480 +0x6a
net/http.Get(...)
 /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/client.go:449
github.com/infracost/infracost/internal/update.getLatestGitHubVersion()
 /home/runner/work/infracost/infracost/internal/update/update.go:173 +0x5f
github.com/infracost/infracost/internal/update.CheckForUpdate(0x0?)
 /home/runner/work/infracost/infracost/internal/update/update.go:67 +0xef
main.startUpdateCheck.func1()
 /home/runner/work/infracost/infracost/cmd/infracost/main.go:229 +0x45
created by main.startUpdateCheck
 /home/runner/work/infracost/infracost/cmd/infracost/main.
```

Since we are using that in our CI/CD, and it will fail the whole job, so it's bothering the users. 
Could you please put it as a high priority issue to be resolved ? 

Thanks

**Comment by vdmgolub** [comment]
@mrhr7 Hey, thank you for the info! Are you able to tell what exact command caused this stack trace?

From what you said and what I can see, you have a v0.10.10 CLI version, and the error happens on checking for the newer versions. Looks like something happens during the API request to GitHub. 

Can you try the following things to see if it fixes the issue?
1. Use `INFRACOST_SKIP_UPDATE_CHECK=true` env var with the CLI commands to skip the newer versions check.
2. Update the CLI to the latest v0.10.11 version.

We'll look into that, but hopefully, this can unblock you right now.

**Comment by mrhr7** [comment]
@vdmgolub , Thanks for the info, I will use the `INFRACOST_SKIP_UPDATE_CHECK=true` for resolving the problem for now. 

Here is the exact command, I am running and getting that stack trace: 
```
infracost breakdown --path plan.json --project-name ${REPO_NAME}/${TF_ENV_FULL_NAME} --sync-usage-file --usage-file ${INFRACOST_USAGE_FILE} --log-level error
```
The plan.json file is being created by `terraform show -json plan.tfplan > plan.json`

**Comment by vdmgolub** [comment]
@mrhr7 Thank you!

I've tried replicating this, but it works fine for me. The panic you get comes from Go's net/http package internals, not from the CLI code, so I'd guess what you see is not connected to the error in this issue. However, the version check should not be so disruptive.

May I ask if this error happened for all runs? Or was it intermittent?

**Comment by mrhr7** [comment]
@vdmgolub, It is intermittent and with the next run of the same infra job, it doesn't happen again.
