### ISSUE TITLE
0.7.1 throws An unexpected error occurred

### ISSUE THREAD

**Issue by syphernl** [infracost/infracost#215]
With 0.7.1 I'm getting "An unexpected error occurred" when we run it and provide it with a pre-made json plan:

```bash
$ infracost --no-color --tfdir "${TF_FOLDER_PATH}" --tfjson "${TF_FOLDER_PATH}/${JSON_PLAN_FILE}"

An unexpected error occurred
runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack(0xc00016cf40, 0xc00016cf10, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
main.main.func3(0xc00016df48, 0xc000001680, 0xc0000303c0)
	/app/cmd/infracost/main.go:168 +0x2ae
panic(0x8f3640, 0xc000c3d440)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/infracost/infracost/internal/providers/terraform/aws.NewRoute53Record(0xc000092380, 0x0, 0xc000963633)
	/app/internal/providers/terraform/aws/route53_record.go:16 +0x8f2
github.com/infracost/infracost/internal/providers/terraform.createResource(0xc000092380, 0x0, 0xc0009635f9)
	/app/internal/providers/terraform/parser.go:46 +0x123
github.com/infracost/infracost/internal/providers/terraform.parseJSON(0xc000560000, 0x23b459, 0x3ffe00, 0x3ffe00, 0x0, 0x0, 0x9233c9, 0x7)
	/app/internal/providers/terraform/parser.go:84 +0x88b
github.com/infracost/infracost/internal/providers/terraform.(*terraformProvider).LoadResources(0xc0000672c0, 0xc00008b300, 0x0, 0x0, 0x7fdfc9da7108, 0xc000130240)
	/app/internal/providers/terraform/provider.go:66 +0x6e
main.defaultCmd.func1(0xc00008b300, 0xc00000d900, 0x0)
	/app/cmd/infracost/default.go:71 +0xaa
github.com/urfave/cli/v2.(*App).RunContext(0xc000001680, 0x9c1a80, 0xc00002a078, 0xc00001e1e0, 0x6, 0x6, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70d
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/app/cmd/infracost/main.go:192 +0x485
Environment:
Infracost v0.7.1
Terraform v0.13.5
```

**Comment by alikhajeh1** [comment]
@syphernl thanks for reporting this, I think #216 should fix this, we'll cut a minor release today

**Comment by alikhajeh1** [comment]
@syphernl can you please try https://github.com/infracost/infracost/releases/tag/v0.7.2 and re-open this issue if you're still running into this issue?

The [homebrew version](https://github.com/Homebrew/homebrew-core/pull/64547) can take a few hours to go live but the binaries are available on GH link I mentioned

**Comment by syphernl** [comment]
@alikhajeh1 Thanks for your quick fix. This has indeed resolved the problem.
