### ISSUE TITLE
Unexpected error occurred [eks node group]

### ISSUE THREAD

**Issue by ChrisMcKee** [infracost/infracost#257]
```
tfenv infracost
  ✔ Running terraform init
  ✔ Running terraform plan
  ✔ Running terraform show

An unexpected error occurred
runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack(0xc000510eb0, 0xc000510e80, 0x1)
        /opt/hostedtoolcache/go/1.14.12/x64/src/runtime/debug/stack.go:24 +0x9d
main.main.func3(0xc000511f48, 0xc000272000, 0xc00003a480)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:168 +0x2a7
panic(0x955420, 0xc000277fc0)
        /opt/hostedtoolcache/go/1.14.12/x64/src/runtime/panic.go:969 +0x166
github.com/infracost/infracost/internal/providers/terraform/aws.NewEKSNodeGroup(0xc0001737a0, 0x0, 0xc0006503d7)
        /home/runner/work/infracost/infracost/internal/providers/terraform/aws/eks_node_group.go:29 +0xe9f
github.com/infracost/infracost/internal/providers/terraform.createResource(0xc0001737a0, 0x0, 0xc00065038d)
        /home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:50 +0x12d
github.com/infracost/infracost/internal/providers/terraform.parseJSON(0xc000400000, 0x49026, 0x78000, 0x78000, 0x0, 0x0, 0x98ad66, 0x7)
        /home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:88 +0x645
github.com/infracost/infracost/internal/providers/terraform.(*terraformProvider).LoadResources(0xc00007f810, 0xc000117600, 0x0, 0x0, 0x9, 0x8)
        /home/runner/work/infracost/infracost/internal/providers/terraform/provider.go:66 +0x6e
main.defaultCmd.func1(0xc000117600, 0xc00000da00, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/default.go:71 +0xaa
github.com/urfave/cli/v2.(*App).RunContext(0xc000272000, 0xa59ae0, 0xc000034110, 0xc00001e1d0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:192 +0x4ac

Environment:
Infracost v0.7.7
Terraform v0.13.5
```

**Comment by alikhajeh1** [comment]
@ChrisMcKee thanks for reporting this! In your terraform's `eks_node_group` resource, do you have an `instance_types` that's set to `[]`? If so, you can set it to `["t3.medium"]` as the [terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#instance_types) mention that is the default. The current infracost code expects an array with 1 item to be set, but I'll change it to check for an empty array too.
