### ISSUE TITLE
An unexpected error occurred running infracost on AWS China

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#400]
When i was trying to apply infracost from current directory (state file) on AWS China I have faced fallowing issue:
```
Loading resources from current directory
  ✔ Running terraform show
An unexpected error occurred
runtime error: index out of range [3] with length 1
goroutine 1 [running]:
runtime/debug.Stack(0xa294e0, 0x1086a00, 0x0)
	/opt/hostedtoolcache/go/1.14.14/x64/src/runtime/debug/stack.go:24 +0x9d
main.handleUnexpectedErr(0xc0001389a0, 0xc00019c820, 0xaaea40, 0xc000301a20)
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:179 +0x1bc
main.main.func1(0xc000217f40, 0xc0001389a0, 0xc000217ef8, 0xc000030420)
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:50 +0xb9
panic(0xaaea40, 0xc000301a20)
	/opt/hostedtoolcache/go/1.14.14/x64/src/runtime/panic.go:969 +0x166
github.com/infracost/infracost/internal/providers/terraform.resourceRegion(0xc000458373, 0xe, 0x5, 0xc0004583fc, 0x4f, 0x0, 0x0, 0x0, 0xee, 0x0, ...)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:196 +0x2d5
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseResourceData(0xc000217820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, 0xc00045805f, ...)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:142 +0x47e
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseResourceData(0xc000217820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, 0xc00045804d, ...)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:158 +0x9f7
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSON(0xc000217820, 0xc0003b0000, 0x37f86, 0x38000, 0xc000296060, 0x0, 0x2, 0x2, 0xc000217828, 0x40cbf8)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:98 +0x4da
github.com/infracost/infracost/internal/providers/terraform.(*terraformProvider).LoadResources(0xc000298000, 0xc000296060, 0xc000296060, 0x0, 0x0, 0x29, 0x0)
	/home/runner/work/infracost/infracost/internal/providers/terraform/provider.go:87 +0xa4
main.defaultMain(0xc0001389a0, 0x0, 0x0)
	/home/runner/work/infracost/infracost/cmd/infracost/default.go:258 +0x4ef
main.defaultCmd.func1(0xc0001eef80, 0xc000204900, 0x0)
	/home/runner/work/infracost/infracost/cmd/infracost/default.go:129 +0x102
github.com/urfave/cli/v2.(*App).RunContext(0xc00019c820, 0xc2e0c0, 0xc0000320c8, 0xc00001e180, 0x3, 0x3, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:122 +0x56a
Environment:
Infracost v0.7.17
Please copy the above output and create a new issue at https://github.com/infracost/infracost/issues/new
```

infracost.yml
```
---
no_color: true
projects:
  terraform:
    - dir: .
      use_state: true
outputs:
  - format: table
    columns: [NAME, HOURLY_COST, MONTHLY_QUANTITY]
```

**Comment by aliscott** [comment]
Thanks @dawidmalina, looks like there's a resource with a non-standard ARN. Which terraform resource types are in this project?

**Comment by dawidmalina** [comment]
The execution for plan will run without issues but no estimation will be provided.
```
  NAME                                                                         MONTHLY QTY  UNIT         PRICE   HOURLY COST  MONTHLY COST   
  module.china.module.alerts_notification.aws_sns_topic.main                                                                                
  └─ Requests                                                                            -  1M requests  0.5255            -             -  
  Total                                                                                                                    -             -  
                                                                                                                                            
  module.china.module.backup_notification.aws_sns_topic.main                                                                                
  └─ Requests                                                                            -  1M requests  0.5255            -             -  
  Total                                                                                                                    -             -  
                                                                                                                                            
  module.china.module.events.aws_lambda_function.lambda                                                                                     
  ├─ Requests                                                                            -  1M requests  0.2102            -             -  
  └─ Duration                                                                            -  GB-seconds    2e-05            -             -  
  Total                                                                                                                    -             -  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_dx_gateway_association.association[0]                                                                 
  ├─ Data processed                                                                      -  GB           0.0000            -             -  
  └─ Transit gateway attachment                                                        730  hours        0.0000       0.0000        0.0000  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.ecr[0]                                                                                   
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.ecrapi[0]                                                                                
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.logs[0]                                                                                  
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.sns[0]                                                                                   
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2_ep01[0]                                                                          
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2messages_ep01[0]                                                                  
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_secretsmanager_ep01[0]                                                               
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssm_ep01[0]                                                                          
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  module.china.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssmmessages_ep01[0]                                                                  
  ├─ Interface endpoint                                                              1,460  hours        0.0000       0.0000        0.0000  
  └─ Data processed                                                                      -  GB           0.0000            -             -  
  Total                                                                                                               0.0000        0.0000  
                                                                                                                                            
  OVERALL TOTAL (USD)                                                                                                 0.0000        0.0000  
```

infracost.yml
```
---
no_color: true
projects:
  terraform:
    - dir: .
      plan_file: plan.tfplan
outputs:
  - format: table
    columns: [NAME, HOURLY_COST, MONTHLY_QUANTITY]
  - format: html
    path: infracost-report.html
```

**Comment by aliscott** [comment]
@dawidmalina I've fixed the runtime error in https://github.com/infracost/infracost/pull/412, but this suggests there's an odd ARN in there which I can't reproduce. Can you run `terraform show -json | jq | grep arn` and see if any don't match the standard `arn:aws:ec2:cn-north-1:999991234567:vpc-endpoint/vpce-012345d888e554cd2` format?

I'm also looking into the zero costs as well.

**Comment by dawidmalina** [comment]
```
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": null,
"arn": null,
"arn": "arn:aws-cn:iam::aws:policy/AmazonSSMManagedInstanceCore",
"arn": "arn:aws-cn:iam::aws:policy/CloudWatchAgentServerPolicy",
"arn": null,
"arn": "arn:aws-cn:iam::111111111111:role/ACCADM",
"arn": "arn:aws-cn:iam::111111111111:policy/AUDITOR",
"arn": "arn:aws-cn:iam::111111111111:role/AUDITOR",
"arn": "arn:aws-cn:iam::111111111111:policy/BILLADM",
"arn": "arn:aws-cn:iam::111111111111:role/BILLADM",
"arn": "arn:aws-cn:iam::111111111111:policy/EC2IAAC",
"arn": "arn:aws-cn:iam::111111111111:role/EC2IAAC",
"arn": "arn:aws-cn:iam::111111111111:role/IAMADM",
"arn": "arn:aws-cn:iam::111111111111:policy/LOGFORW",
"arn": "arn:aws-cn:iam::111111111111:role/LOGFORW",
"arn": "arn:aws-cn:iam::111111111111:role/rds-directoryservice-access-role",
"arn": "arn:aws-cn:iam::111111111111:role/ASECADM",
"arn": "arn:aws-cn:iam::111111111111:policy/WLADM",
"arn": "arn:aws-cn:iam::111111111111:role/WLADM",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:sns:cn-north-1:111111111111:ALERTS",
"arn": "arn:aws-cn:sns:cn-north-1:111111111111:ALERTS",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-plan:26b0123f-d7e8-4c23-8a73-e8f5aa26d41a",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-plan:e965a96d-6f09-4a48-91be-86d57048b6f9",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-plan:6a5ef812-97bd-4be9-a51f-a1dcd890d4e7",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-plan:2376cefe-e497-40ae-866d-bd66fddae6ab",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-plan:7fa583c1-0221-4e99-8291-8df8cae9e95c",
"arn": "arn:aws-cn:backup:cn-north-1::backup-plan:04fc1e49-b1bc-4aa4-a025-5b494b00f1ad",
"arn": "arn:aws-cn:backup:cn-north-1:111111111111:backup-vault:VAULT",
"arn": "arn:aws-cn:iam::111111111111:role/BACKUP",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:sns:cn-north-1:111111111111:BACKUPS",
"arn": "arn:aws-cn:sns:cn-north-1:111111111111:BACKUPS",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-2ghvdv",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-8ba1bb",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-hyenxr",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-up9doa",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-qwyu6r",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-eczp5d",
"arn": "arn:aws-cn:config:cn-north-1:111111111111:config-rule/config-rule-vpq5tg",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-CONFIG",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-IG",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-USER",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-CT",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-ROOT",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-S3",
"arn": "arn:aws-cn:events:cn-north-1:111111111111:rule/SECAUT-SG",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:lambda:cn-north-1:111111111111:function:SECAUT",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-flow-log/fl-08fecbbdbcbc08bff",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:network-acl/acl-0e27b6180409b6fbd",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:security-group/sg-052db8cd5a82c076c",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:security-group/sg-011c1e4f706406b76",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:subnet/subnet-0c7179998173969b2",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:subnet/subnet-08f2a7a4402ee9662",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc/vpc-0cedefedc60e678c5",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:dhcp-options/dopt-0f5de364be0787eb6",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-0828c3602fc6f6aa2",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-084fee9c97c682979",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-0aab3fc0d66b45158",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-05cb4b31d6219669b",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-0b388b7a0e4c64954",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-058fa66d258240a24",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-0cdf9af37af99e6b6",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-07fe5c7fb79487854",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-01631d41f5a0dc9eb",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpc-endpoint/vpce-0b33f5d669e44b77f",
"arn": "arn:aws-cn:ec2:cn-north-1:111111111111:vpn-gateway/vgw-016f13f11f314fea0",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
"arn": "arn:aws-cn:iam::aws:policy/service-role/AWSConfigRole",
"arn": "arn:aws-cn:iam::111111111111:policy/config_recorder_config_policy",
"arn": "arn:aws-cn:iam::111111111111:policy/pass_role",
"arn": "arn:aws-cn:iam::111111111111:policy/config_perm_policy",
"arn": "arn:aws-cn:iam::111111111111:policy/config_bucket_policy",
"arn": "arn:aws-cn:iam::111111111111:role/CONFIG",
"arn": "arn:aws-cn:iam::111111111111:policy/SECAUT",
"arn": "arn:aws-cn:iam::111111111111:role/SECAUT",
"arn": "arn:aws-cn:sts::111111111111:assumed-role/ACCADM/1111111111111111111",
```

**Comment by dawidmalina** [comment]
```
            {
              "address": "module.base_iam.data.aws_iam_policy.amazon_guard_duty_full_access",
              "mode": "data",
              "type": "aws_iam_policy",
              "name": "amazon_guard_duty_full_access",
              "provider_name": "registry.terraform.io/hashicorp/aws",
              "schema_version": 0,
              "values": {
                "arn": null,
                "description": null,
                "id": null,
                "name": null,
                "path": null,
                "policy": null
              }
```
```
            {
              "address": "module.base_iam.data.aws_iam_policy.amazon_macie_full_access",
              "mode": "data",
              "type": "aws_iam_policy",
              "name": "amazon_macie_full_access",
              "provider_name": "registry.terraform.io/hashicorp/aws",
              "schema_version": 0,
              "values": {
                "arn": null,
                "description": null,
                "id": null,
                "name": null,
                "path": null,
                "policy": null
              }
```
```
            {
              "address": "module.base_iam.data.aws_iam_policy.compute_optimizer_read_only_access",
              "mode": "data",
              "type": "aws_iam_policy",
              "name": "compute_optimizer_read_only_access",
              "provider_name": "registry.terraform.io/hashicorp/aws",
              "schema_version": 0,
              "values": {
                "arn": null,
                "description": null,
                "id": null,
                "name": null,
                "path": null,
                "policy": null
             }
```

**Comment by aliscott** [comment]
@dawidmalina yeah this looks like the nulls were causing issues, thanks! The fix will go out in the next release (today).

For the zero prices, this is an issue with the AWS bulk pricing API. I've filed a ticket with AWS and created a new issue here to track it: https://github.com/infracost/infracost/issues/417.
