### ISSUE TITLE
Issue running breakdown on EFS resources

### ISSUE THREAD

**Issue by sushant-pradhan** [infracost/infracost#500]
Environment:
terraform 0.12.29
infracost: 0.8.0
OS: debian buster

Command:
```bash
terraform init --backend=true --backend-config=backend.tfvars
infracost breakdown --path . --terraform-use-state --log-level warn
```

Error:
```bash
+ infracost breakdown --path . --terraform-use-state --log-level warn

Error: An unexpected error occurred

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x203000, 0x203000, 0x203000)
	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc000144840, 0xa96760, 0xf6bbd0)
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:220 +0x45
main.main.func1(0xc000135ec8, 0xc000144840, 0xc000034420)
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:39 +0xa5
panic(0xa96760, 0xf6bbd0)
	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/providers/terraform/aws.calculateProvisionedThroughput(0x0, 0xc0000ab620, 0x0, 0x0, 0x0)
	/home/runner/work/infracost/infracost/internal/providers/terraform/aws/efs_file_system.go:135 +0x14d
github.com/infracost/infracost/internal/providers/terraform/aws.NewEFSFileSystem(0xc0003a2500, 0x0, 0xc0007dd402)
	/home/runner/work/infracost/infracost/internal/providers/terraform/aws/efs_file_system.go:44 +0x1b4a
github.com/infracost/infracost/internal/providers/terraform.(*Parser).createResource(0xc000135720, 0xc0003a2500, 0x0, 0x23)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:65 +0x174
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSONResources(0xc000135720, 0x23b00, 0xfb26e8, 0x0, 0x0, 0xc0001dc090, 0x5, 0xc0007dc000, 0x23bee, 0x0, ...)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:102 +0x4d1
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSON(0xc000069720, 0xc000242000, 0x23bee, 0x38000, 0xc0001dc090, 0x0, 0xc000069728, 0x8f3ba6, 0xc0001dc090, 0x0, ...)
	/home/runner/work/infracost/infracost/internal/providers/terraform/parser.go:123 +0x892
github.com/infracost/infracost/internal/providers/terraform.(*DirProvider).LoadResources(0xc000164510, 0xc0001dc090, 0xc0001dc090, 0x0, 0x0)
	/home/runner/work/infracost/infracost/internal/providers/terraform/dir_provider.go:104 +0x145
main.runMain(0xc00020c000, 0xc000144840, 0x0, 0x0)
	/home/runner/work/infracost/infracost/cmd/infracost/run.go:74 +0x388
main.breakdownCmd.func1(0xc00020c000, 0xc0001c8f00, 0x0, 0x5, 0x0, 0x0)
	/home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:38 +0xdf
github.com/spf13/cobra.(*Command).execute(0xc00020c000, 0xc0001c8eb0, 0x5, 0x5, 0xc00020c000, 0xc0001c8eb0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e1680, 0x351, 0xc000135ee8, 0x7)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/home/runner/work/infracost/infracost/cmd/infracost/main.go:171 +0xd3e

Environment:
Infracost v0.8.0

Please copy the above output and create a new issue at https://github.com/infracost/infracost/issues/new
```

**Comment by alikhajeh1** [comment]
Fixed in v0.8.1
