### ISSUE TITLE
runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by c0ntax** [infracost/infracost#581]
I just got the following error when running a sync-user-file

`
$ infracost breakdown --sync-usage-file --usage-file infracost-usage.yml --path=.
Detected Terraform directory at .
  ✔ Running terraform plan
  ✔ Running terraform show

Error: An unexpected error occurred

runtime error: index out of range [-1]
goroutine 1 [running]:
runtime/debug.Stack(0xc000b46fc0, 0x240, 0x5555555555555555)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc0000d4b00, 0xaf6da0, 0xc000b16828)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:220 +0x45
main.main.func1(0xc000373ec8, 0xc0000d4b00, 0xc0000304e0)
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:39 +0xa5
panic(0xaf6da0, 0xc000b16828)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/usage.syncResourcesUsage(0xc0009d4000, 0x2ec, 0x400, 0xc0009cfbc0, 0xc0001eb920, 0x1, 0x1, 0x0)
        /home/runner/work/infracost/infracost/internal/usage/usage_file.go:71 +0x59e
github.com/infracost/infracost/internal/usage.SyncUsageData(0xc0001ffab0, 0xc0001eb920, 0x7fff6975565b, 0x13, 0x1, 0xc0008dd150)
        /home/runner/work/infracost/infracost/internal/usage/usage_file.go:47 +0x85
main.runMain(0xc000228000, 0xc0000d4b00, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/run.go:84 +0x4ff
main.breakdownCmd.func1(0xc000228000, 0xc0001e27c0, 0x0, 0x4, 0x0, 0x0)
        /home/runner/work/infracost/infracost/cmd/infracost/breakdown.go:40 +0x106
github.com/spf13/cobra.(*Command).execute(0xc000228000, 0xc0001e2780, 0x4, 0x4, 0xc000228000, 0xc0001e2780)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f1680, 0x351, 0xc0000c5ee8, 0x7)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/infracost/infracost/cmd/infracost/main.go:171 +0xd3e

Environment:
Infracost v0.8.3
`

**Comment by aliscott** [comment]
Thanks for reporting @c0ntax, this has been fixed in #582 and will be released in v0.8.4 tomorrow.

**Comment by c0ntax** [comment]
Thank you @aliscott . I look forward to getting hold of this!

**Comment by alikhajeh1** [comment]
@c0ntax v0.8.4 is live with the fix :)
