### ISSUE TITLE
Infracost docker image runs with root

### ISSUE THREAD

**Issue by camaeel** [infracost/infracost#861]
Infracost docker image requires to be started with root or to create a child image with dedicated user created. 
If I try to run it with other user:
```
$ docker run -it --rm --entrypoint sh -v ~/src/\[other\]/opa-tf/tmp/tfplan.json:/tfplan.json -u 1000:1000 infracost/infracost
```
 it throws a segmentation fault:
```
/root $ infracost breakdown --format json --path /tfplan.json
Error: mkdir /.config: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd039f7]

goroutine 1 [running]:
github.com/infracost/infracost/internal/apiclient.ReportCLIError(0x0, 0x13a3020, 0xc0001c0cc0, 0x44df2c, 0x20)
	/app/internal/apiclient/errors.go:12 +0x37
main.handleCLIError(0x0, 0x13a3020, 0xc0001c0cc0)
	/app/cmd/infracost/main.go:156 +0x79
main.main.func1(0xc000135ec8, 0x0, 0xc000074120)
	/app/cmd/infracost/main.go:32 +0xbf
panic(0xf359a0, 0x192a8f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/config.(*RunContext).SetContextValue(...)
	/app/internal/config/run_context.go:55
main.main.func2(0xc000195b80, 0xc0001be6c0, 0x0, 0x4, 0x0, 0x0)
	/app/cmd/infracost/main.go:67 +0x66
github.com/spf13/cobra.(*Command).execute(0xc000195b80, 0xc0001be680, 0x4, 0x4, 0xc000195b80, 0xc0001be680)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:831 +0x582
github.com/spf13/cobra.(*Command).ExecuteC(0xc000195400, 0x351, 0xc000135ee8, 0x7)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/app/cmd/infracost/main.go:121 +0xb79
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd05546]

goroutine 6 [running]:
github.com/infracost/infracost/internal/update.skipUpdateCheck(0x0, 0x0)
	/app/internal/update/update.go:93 +0x26
github.com/infracost/infracost/internal/update.CheckForUpdate(0x0, 0x0, 0x0, 0x0)
	/app/internal/update/update.go:30 +0x32
main.startUpdateCheck.func1(0x0, 0xc000074120)
	/app/cmd/infracost/main.go:126 +0x38
created by main.startUpdateCheck
	/app/cmd/infracost/main.go:125 +0x49
```

**Comment by aliscott** [comment]
Thanks @camaeel I've been able to reproduce it. As a workaround at the moment you can add something like `-e HOME=/tmp` to the Docker command.

**Comment by camaeel** [comment]
Thanks, @aliscott 

Workaround, works like a charm.

**Comment by alikhajeh1** [comment]
FWIW, this issue also popped-up when @sinabakh was working on the https://github.com/infracost/infracost-jenkins integration, though in there we went with `--user=root` to work around it.

**Comment by sinabakh** [comment]
It would be great if we could create an image with a non-root user.

**Comment by aliscott** [comment]
Thanks for reporting this @camaeel 😄. I've merged a fix in https://github.com/infracost/infracost/pull/862 that will be in the next release.

**Comment by alikhajeh1** [comment]
Should we create a new ticket to update all of Dockerfiles to run as non-root? There's no reason they'd need root, right?
